"""add favorite_food

Revision ID: 4fead3941268
Revises: eabf5431dd99
Create Date: 2026-09-19 15:45:59.328444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fead3941268'
down_revision: Union[str, Sequence[str], None] = 'eabf5431dd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('cuisine', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ingredients', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingredient_status', sa.Enum('pending', 'ready', 'failed', name='ingredientstatus'), nullable=False),
    sa.Column('ingredient_error', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ingredients_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_favorite_food_per_user')
    )
    op.create_index(op.f('ix_favorite_food_ingredient_status'), 'favorite_food', ['ingredient_status'], unique=False)
    op.create_index(op.f('ix_favorite_food_name'), 'favorite_food', ['name'], unique=False)
    op.create_index(op.f('ix_favorite_food_user_id'), 'favorite_food', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_food_user_id'), table_name='favorite_food')
    op.drop_index(op.f('ix_favorite_food_name'), table_name='favorite_food')
    op.drop_index(op.f('ix_favorite_food_ingredient_status'), table_name='favorite_food')
    op.drop_table('favorite_food')
    # ### end Alembic commands ###
    # Postgres keeps the enum type after its table is dropped.
    if op.get_bind().dialect.name == "postgresql":
        sa.Enum(name="ingredientstatus").drop(op.get_bind(), checkfirst=True)
