"""initial schema

Revision ID: eabf5431dd99
Revises: 
Create Date: 2026-09-19 13:52:09.759432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eabf5431dd99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='friendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friend_pair')
    )
    op.create_index(op.f('ix_friend_friend_id'), 'friend', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friend_status'), 'friend', ['status'], unique=False)
    op.create_index(op.f('ix_friend_user_id'), 'friend', ['user_id'], unique=False)
    op.create_table('grocery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('purchased_on', sa.Date(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_item_category'), 'grocery_item', ['category'], unique=False)
    op.create_index(op.f('ix_grocery_item_consumed'), 'grocery_item', ['consumed'], unique=False)
    op.create_index(op.f('ix_grocery_item_expires_on'), 'grocery_item', ['expires_on'], unique=False)
    op.create_index(op.f('ix_grocery_item_name'), 'grocery_item', ['name'], unique=False)
    op.create_index(op.f('ix_grocery_item_owner_id'), 'grocery_item', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grocery_item_owner_id'), table_name='grocery_item')
    op.drop_index(op.f('ix_grocery_item_name'), table_name='grocery_item')
    op.drop_index(op.f('ix_grocery_item_expires_on'), table_name='grocery_item')
    op.drop_index(op.f('ix_grocery_item_consumed'), table_name='grocery_item')
    op.drop_index(op.f('ix_grocery_item_category'), table_name='grocery_item')
    op.drop_table('grocery_item')
    op.drop_index(op.f('ix_friend_user_id'), table_name='friend')
    op.drop_index(op.f('ix_friend_status'), table_name='friend')
    op.drop_index(op.f('ix_friend_friend_id'), table_name='friend')
    op.drop_table('friend')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
    # Postgres keeps the enum type after its table is dropped; a later upgrade
    # would then fail with "type friendstatus already exists".
    if op.get_bind().dialect.name == "postgresql":
        sa.Enum(name="friendstatus").drop(op.get_bind(), checkfirst=True)
