"""feasts, attendees and notifications

Revision ID: 21bb049b161b
Revises: 2b7ca72afb84
Create Date: 2026-09-19 17:27:04.273829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21bb049b161b'
down_revision: Union[str, Sequence[str], None] = '2b7ca72afb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feast_host_id'), 'feast', ['host_id'], unique=False)
    op.create_index(op.f('ix_feast_scheduled_for'), 'feast', ['scheduled_for'], unique=False)
    op.create_table('feast_attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Enum('invited', 'accepted', 'declined', name='inviteresponse'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feast_id'], ['feast.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feast_id', 'user_id', name='uq_feast_attendee')
    )
    op.create_index(op.f('ix_feast_attendee_feast_id'), 'feast_attendee', ['feast_id'], unique=False)
    op.create_index(op.f('ix_feast_attendee_response'), 'feast_attendee', ['response'], unique=False)
    op.create_index(op.f('ix_feast_attendee_user_id'), 'feast_attendee', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('feast_id', sa.Integer(), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'sent', 'failed', name='deliverystatus'), nullable=False),
    sa.Column('delivery_error', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feast_id'], ['feast.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_delivery_status'), 'notification', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_notification_feast_id'), 'notification', ['feast_id'], unique=False)
    op.create_index(op.f('ix_notification_kind'), 'notification', ['kind'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_kind'), table_name='notification')
    op.drop_index(op.f('ix_notification_feast_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_delivery_status'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_feast_attendee_user_id'), table_name='feast_attendee')
    op.drop_index(op.f('ix_feast_attendee_response'), table_name='feast_attendee')
    op.drop_index(op.f('ix_feast_attendee_feast_id'), table_name='feast_attendee')
    op.drop_table('feast_attendee')
    op.drop_index(op.f('ix_feast_scheduled_for'), table_name='feast')
    op.drop_index(op.f('ix_feast_host_id'), table_name='feast')
    op.drop_table('feast')
    # ### end Alembic commands ###
    # Postgres keeps enum types after their tables are dropped.
    if op.get_bind().dialect.name == "postgresql":
        for name in ("inviteresponse", "deliverystatus"):
            sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
