"""food preferences: rename favorite_food, add preference

Revision ID: 2b7ca72afb84
Revises: 4fead3941268
Create Date: 2026-09-19 16:27:31.992707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b7ca72afb84'
down_revision: Union[str, Sequence[str], None] = '4fead3941268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Rename favorite_food -> food_preference and add the like/dislike column.

    Written by hand rather than autogenerated: autogenerate reads a rename as a
    drop plus an add, which would discard every existing row.
    """
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    op.rename_table("favorite_food", "food_preference")

    # Existing rows were all foods the user liked.
    preference = sa.Enum("like", "dislike", name="preference")
    preference.create(bind, checkfirst=True)
    op.add_column(
        "food_preference",
        sa.Column("preference", preference, nullable=False, server_default="like"),
    )
    # The default existed only to backfill existing rows; the app always sets
    # the value explicitly. SQLite cannot ALTER a column to drop a default, and
    # a leftover default there is harmless, so only Postgres gets this.
    if is_pg:
        op.alter_column("food_preference", "preference", server_default=None)

    if is_pg:
        op.execute("ALTER TABLE food_preference RENAME CONSTRAINT "
                   "uq_favorite_food_per_user TO uq_food_preference_per_user")
        # Postgres keeps the old auto-generated PK index name after a table
        # rename; rename it too so nothing in the schema still says favorite_food.
        op.execute("ALTER INDEX favorite_food_pkey RENAME TO food_preference_pkey")
        op.execute("ALTER SEQUENCE favorite_food_id_seq RENAME TO food_preference_id_seq")
        for old, new in [
            ("ix_favorite_food_user_id", "ix_food_preference_user_id"),
            ("ix_favorite_food_name", "ix_food_preference_name"),
            ("ix_favorite_food_ingredient_status", "ix_food_preference_ingredient_status"),
        ]:
            op.execute(f"ALTER INDEX {old} RENAME TO {new}")
    else:
        # SQLite cannot rename indexes or constraints. Batch mode rebuilds the
        # table so the unique constraint comes back under its new name.
        with op.batch_alter_table("food_preference") as batch:
            batch.drop_constraint("uq_favorite_food_per_user", type_="unique")
            batch.create_unique_constraint("uq_food_preference_per_user", ["user_id", "name"])
        for old in ("ix_favorite_food_user_id", "ix_favorite_food_name",
                    "ix_favorite_food_ingredient_status"):
            op.drop_index(old, table_name="food_preference")
        op.create_index("ix_food_preference_user_id", "food_preference", ["user_id"])
        op.create_index("ix_food_preference_name", "food_preference", ["name"])
        op.create_index("ix_food_preference_ingredient_status", "food_preference",
                        ["ingredient_status"])

    op.create_index("ix_food_preference_preference", "food_preference", ["preference"])


def downgrade() -> None:
    """Back to favorite_food. Dislikes are dropped — they have nowhere to go."""
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    op.execute("DELETE FROM food_preference WHERE preference = 'dislike'")
    op.drop_index("ix_food_preference_preference", table_name="food_preference")
    op.drop_column("food_preference", "preference")
    sa.Enum(name="preference").drop(bind, checkfirst=True)

    if is_pg:
        op.execute("ALTER TABLE food_preference RENAME CONSTRAINT "
                   "uq_food_preference_per_user TO uq_favorite_food_per_user")
        op.execute("ALTER INDEX food_preference_pkey RENAME TO favorite_food_pkey")
        op.execute("ALTER SEQUENCE food_preference_id_seq RENAME TO favorite_food_id_seq")
        for new, old in [
            ("ix_food_preference_user_id", "ix_favorite_food_user_id"),
            ("ix_food_preference_name", "ix_favorite_food_name"),
            ("ix_food_preference_ingredient_status", "ix_favorite_food_ingredient_status"),
        ]:
            op.execute(f"ALTER INDEX {new} RENAME TO {old}")
    else:
        with op.batch_alter_table("food_preference") as batch:
            batch.drop_constraint("uq_food_preference_per_user", type_="unique")
            batch.create_unique_constraint("uq_favorite_food_per_user", ["user_id", "name"])
        for new in ("ix_food_preference_user_id", "ix_food_preference_name",
                    "ix_food_preference_ingredient_status"):
            op.drop_index(new, table_name="food_preference")
        op.create_index("ix_favorite_food_user_id", "food_preference", ["user_id"])
        op.create_index("ix_favorite_food_name", "food_preference", ["name"])
        op.create_index("ix_favorite_food_ingredient_status", "food_preference",
                        ["ingredient_status"])

    op.rename_table("food_preference", "favorite_food")
