"""Add expo_push_token to User

Revision ID: 876c4b91f3d5
Revises: c9d4e88b12f3
Create Date: 2026-09-20 18:56:29.324544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '876c4b91f3d5'
down_revision: Union[str, Sequence[str], None] = 'c9d4e88b12f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('expo_push_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'expo_push_token')
    # ### end Alembic commands ###
